export const WEIBO_ENDPOINTS = {
  forYou: '/ajax/feed/unreadfriendstimeline',
  following: '/ajax/feed/friendstimeline',
  groupTimeline: '/ajax/feed/groupstimeline',
  exploreHot: '/ajax/feed/hottimeline',
  exploreGroups: '/ajax/feed/allGroups',
  sideCards: '/ajax/side/cards',
  statusDetail: '/ajax/statuses/show',
  statusComments: '/ajax/statuses/buildComments',
  statusLongText: '/ajax/statuses/longtext',
  statusConfig: '/ajax/statuses/config',
  setLike: '/ajax/statuses/setLike',
  cancelLike: '/ajax/statuses/cancelLike',
  setCommentLike: '/ajax/statuses/updateLike',
  cancelCommentLike: '/ajax/statuses/destroyLike',
  normalRepost: '/ajax/statuses/normal_repost',
  statusDestroy: '/ajax/statuses/destroy',
  destroyComment: '/ajax/statuses/destroyComment',
  commentCreate: '/ajax/comments/create',
  commentReply: '/ajax/comments/reply',
  statusUpdate: '/ajax/statuses/update',
  profileInfo: '/ajax/profile/info',
  profileDetail: '/ajax/profile/detail',
  profilePosts: '/ajax/statuses/mymblog',
  followCreate: '/ajax/friendships/create',
  followDestroy: '/ajax/friendships/destory',
  searchBand: '/ajax/side/searchBand',
  mineBand: '/ajax/statuses/mineBand',
  entertainmentBand: '/ajax/statuses/entertainment',
  lifeBand: '/ajax/statuses/life',
  socialBand: '/ajax/statuses/social',
  searchSide: '/ajax/side/search',
  favoritesAll: '/ajax/favorites/all_fav',
  likedStatuses: '/ajax/statuses/likelist',
  createFavorites: '/ajax/statuses/createFavorites',
  destroyFavorites: '/ajax/statuses/destoryFavorites',
  mentions: '/ajax/statuses/mentions',
  comments: '/ajax/message/cmt',
  likes: '/ajax/message/attitudes',
  remind: '/ajax/message/remind',
  friends: '/ajax/friendships/friends',

  /** m.weibo.cn unread remind endpoint (requires background fetch) */
  mweiboRemind: 'https://m.weibo.cn/api/remind/unread',
} as const

type WeiboEndpointKey = keyof typeof WEIBO_ENDPOINTS
export type WeiboEndpointPath = (typeof WEIBO_ENDPOINTS)[WeiboEndpointKey]
