name: Bug Report
description: Report a bug
title: '[Bug]: '
labels: [Bug]

body:
  - type: markdown
    attributes:
      value: |
        标题不填或随便写类似「bug」「错误」「有问题」的 issue 将直接关闭。

        功能请求请不要在这里提交，请使用[功能请求模板](https://github.com/nnecec/xb/issues/new?template=feature_request_template.yaml)。

        若遇到页面相关问题（比如某页面下出现了不该出现的元素），建议一并附上发生问题的页面链接。

  - type: textarea
    attributes:
      label: 环境信息
      description: 请填写扩展版本、浏览器版本等信息。
      placeholder: |
        - 浏览器（如 Google Chrome）：
        - xb 版本（如 0.1.0）：

        如果你修改了 xb 的设置，请写在下面以方便排查问题（可粗略写成类似「设置了 ×× 后出现这个问题」）：
      value: |
        - 浏览器（如 Google Chrome）：
        - xb 版本（如 0.1.0）：

        如果你修改了 xb 的设置，请写在下面以方便排查问题（可粗略写成类似「设置了 ×× 后出现这个问题」）：
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 安装来源
      options:
        - Chrome Web Store
        - Firefox Add-ons
        - Edge Add-ons
        - GitHub Release
        - 自行编译
    validations:
      required: true

  - type: input
    attributes:
      label: 页面地址
      description: 如果涉及特定页面，请提供页面地址
      placeholder: '例如：https://weibo.com/u/1234567890'

  - type: textarea
    attributes:
      label: 问题描述
      description: 请详细描述你遇到的问题，与UI相关时最好附带截图。
      placeholder: |
        请预先搜索此问题是否在其他 issue 中出现过
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为
      description: 如果产品不符合预期，请提供你认为应该是什么行为。
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 最终确认
      description: 请确认以下所有内容后再提交。
      options:
        - label: 我确认在停用 xb 并强制刷新后，问题不再出现。
          required: false
        - label: 我确认我正在使用最新的 xb 版本。
          required: false

  - type: checkboxes
    attributes:
      label: 参与贡献
      options:
        - label: 我将自行创建 PR 进行修复
          required: false
